steps:
  - id: create bucket
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [ 'gsutil', 'mb', '-l', 'europe-west3', '--retention', '3600s', 'gs://${PROJECT_ID}_serenity_report' ]

# FIXME pass location as argument