steps:
  - id: check files
    name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        find .

  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mvn verify || touch .fail && if test ! -e target/site/serenity; then exit 1; fi


# FIXME, upload takes ages, cam we make it so we upload html report dependencies only when serenity version changes?
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp','-r', '-J','./target/site/serenity','gs://example-3926-bucket']

  - id: check if failed
    name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ -f .fail ]]; then exit 1; fi

# different way of doing artifacts
# artifacts:
#   objects:
#     location: 'gs://example-3926-bucket/'
#     paths: ['./target/site/serenity']