steps:
  - name: maven:3-jdk-8
    entrypoint: bash
    args: ['mvn verify || true']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp','-r','./target/site/serenity','gs://example-3926-bucket']

# different way of doing artifacts
# artifacts:
#   objects:
#     location: 'gs://example-3926-bucket/'
#     paths: ['./target/site/serenity']