# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  integrationtest:
    docker:
      - image: circleci/openjdk:8u171-jdk-browsers
    working_directory: ~/repo


    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # run tests!
      - run: mvn verify -DMAILOSAUR_API_KEY=$MAILOSAUR_API_KEY

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store_test_results:
          path: target

      - store_artifacts:
          path: target/site/serenity
          destination: serenity



      #- slack/status:
      #    fail_only: true
      #    mentions: 'globalworming,Matthias Hilscher'
      #    failure_message: "check https://onlinetermine.zollsoft.de/patientenTermine.php?uniqueident=606038492079e"
      #    webhook:

orbs:
  slack: circleci/slack@3.4.2

workflows:
  version: 2
  integrationtest:
    jobs:
      - integrationtest