# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  integrationTest:
    docker:
      - image: circleci/openjdk:8u171-jdk-browsers
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - m2--{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - m2--

      #- run: mvn dependency:go-offline

      #- run:
      #    name: Download Selenium
      #    command: |
      #      curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      #
      #- run:
      #    name: Start Selenium
      #    command: |
      #      mkdir selenium-log
      #      java -jar selenium-server-standalone-3.5.3.jar -log selenium-log/selenium.log
      #    background: true

      # run tests!
      - run: mvn verify -DMAILOSAUR_API_KEY=$MAILOSAUR_API_KEY

      - save_cache:
          paths:
            - ~/.m2
          key: m2--{{ checksum "pom.xml" }}


      - store_test_results:
          path: target/failsafe-reports

      - store_artifacts:
          path: target/site/serenity
          destination: serenity

      - aws-s3/copy:
          arguments: "--recursive --acl public-read-write"
          from: target/site/serenity
          to: 's3://serenity-bdd-report'

      - slack/status:
          fail_only: false
          mentions: 'globalworming'
          failure_message: "failure, check latest report at:"
          webhook: $SLACK

workflows:
  test:
    jobs:
      - integrationTest

orbs:
  slack: circleci/slack@3.4.2
  aws-s3: circleci/aws-s3@2.0.0
