pipeline {
  agent {
      docker {
          image 'maven:3.8.1-openjdk-8'
          args '-v $HOME/.m2:/root/.m2'
      }
  }

  stages {
    stage('e2e') {
        steps {
            sh "mvn clean verify -DMAILOSAUR_API_KEY=fixme -Dproperties=`pwd`/serenity.remote.properties"
        }

        post {
            always {
                junit testResults: 'target/failsafe-reports/**/*.xml'

                 publishHTML(target: [
                                        reportName : 'Serenity',
                                        reportDir:   'target/site/serenity',
                                        reportFiles: 'index.html',
                                        keepAll:     true,
                                        alwaysLinkToLastBuild: true,
                                        allowMissing: false
                 ])
                s3Upload acl: 'PublicRead', bucket: 's3://serenity-bdd-report', file: 'target/site/serenity/serenity-summary.html'
            }
        }
    }



  }
}