pipeline {
    agent {
        docker {
            image 'maven:3.8.1-openjdk-8'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    tools {
        'org.jenkinsci.plugins.docker.commons.tools.DockerTool' 'docker'
    }

    stages {
        stage('Build') {
            steps {
                def dockerHome = tool 'docker'
                env.PATH = "${dockerHome}/bin:${env.PATH}"
                echo sh(returnStdout: true, script: 'env')
                sh "docker run --rm -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618"
                sh "mvn clean verify -Dproperties=`pwd`/serenity.remote.properties"
            }

             post { always {
                junit  testResults: 'target/failsafe-reports/**/*.xml', keepLongStdio: true

                publishHTML(target: [
                        reportName : 'Serenity',
                        reportDir:   'target/site/serenity',
                        reportFiles: 'index.html',
                        keepAll:     true,
                        alwaysLinkToLastBuild: true,
                        allowMissing: false
                ])

                emailext mimeType: 'text/html',
                        body: '${JELLY_SCRIPT, template="html"}',
                        attachLog: true, attachmentsPattern: '**/serenity-summary.html',
                        to: 'notify@example.com',
                        subject: "Build: ${currentBuild.currentResult}"
             } }
        }

    }
}